name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
#        with:
#          cache: 'pnpm'

      - name: Install and Build ğŸ”§
        run: |
          pnpm install --no-frozen-lockfile
          pnpm run build:github
          touch dist/.nojekyll

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: dist # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch

      # æ¨åˆ°æœåŠ¡å™¨
      - name: Deploy to Server # ç¬¬äºŒæ­¥ï¼Œrsyncæ¨æ–‡ä»¶
        uses: AEnterprise/rsync-deploy@v1.0 # ä½¿ç”¨åˆ«äººåŒ…è£…å¥½çš„æ­¥éª¤é•œåƒ
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }} # å¼•ç”¨é…ç½®ï¼ŒSSHç§é’¥
          ARGS: -avz --delete --exclude='*.pyc' # rsyncå‚æ•°ï¼Œæ’é™¤.pycæ–‡ä»¶
          SERVER_PORT: ${{ secrets.SSH_PORT }} # SSHç«¯å£
          FOLDER: ./dist # è¦æ¨é€çš„æ–‡ä»¶å¤¹ï¼Œè·¯å¾„ç›¸å¯¹äºä»£ç ä»“åº“çš„æ ¹ç›®å½•
          SERVER_IP: ${{ secrets.SSH_HOST }} # å¼•ç”¨é…ç½®ï¼ŒæœåŠ¡å™¨çš„hoståï¼ˆIPæˆ–è€…åŸŸådomain.comï¼‰
          USERNAME: ${{ secrets.SSH_USER }} # å¼•ç”¨é…ç½®ï¼ŒæœåŠ¡å™¨ç™»å½•å
          SERVER_DESTINATION: project/runcodeclient # éƒ¨ç½²åˆ°ç›®æ ‡æ–‡ä»¶å¤¹

      # nginx é‡å¯
      - name: Restart server # ç¬¬ä¸‰æ­¥ï¼Œé‡å¯æœåŠ¡
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }} # ä¸‹é¢ä¸‰ä¸ªé…ç½®ä¸ä¸Šä¸€æ­¥ç±»ä¼¼
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }} # SSHç«¯å£
          key: ${{ secrets.DEPLOY_KEY }}
          # é‡å¯çš„è„šæœ¬ï¼Œæ ¹æ®è‡ªèº«æƒ…å†µåšç›¸åº”æ”¹åŠ¨ï¼Œä¸€èˆ¬è¦åšçš„æ˜¯migrateæ•°æ®åº“ä»¥åŠé‡å¯æœåŠ¡å™¨
          script: |
            nginx -s reload